In [ ]:
"""Ejercicio 1

Investigue y defina:
● ¿Qué es un cuaderno (notebook) Jupyter? ¿Que es una celda? ¿Que tipos de celdas existen?
● ¿Qué es un entorno de ejecución? ¿Cuánto tiempo dura una sesión de un entorno?



¿Qué es un cuaderno (notebook) Jupyter?
Un cuaderno Jupyter es una aplicación web interactiva que permite crear y compartir documentos que contienen código ejecutable, ecuaciones, visualizaciones y texto narrativo. Se utiliza principalmente para el análisis de datos, aprendizaje automático, simulaciones y otras tareas relacionadas con la programación. Los cuadernos Jupyter son populares porque permiten ejecutar código de manera secuencial y ver los resultados en tiempo real, lo que es útil para experimentar y documentar procesos.

¿Qué es una celda?
En un cuaderno Jupyter, una celda es una unidad de trabajo donde puedes escribir y ejecutar contenido. Las celdas permiten estructurar y organizar el trabajo en un cuaderno, separando diferentes tipos de contenido como código, texto o visualizaciones.

Tipos de celdas en un cuaderno Jupyter:
Celdas de código: Son celdas en las que se escribe código en un lenguaje de programación, como Python. Cuando se ejecuta una celda de código, el contenido se envía al kernel para ser procesado, y los resultados (salida del código) se muestran justo debajo de la celda.

Celdas de texto (Markdown): Estas celdas permiten escribir texto en formato Markdown, lo que incluye títulos, listas, enlaces, imágenes, y más. Son útiles para agregar descripciones, explicaciones, y documentación en el cuaderno.

Celdas de salida: Estas celdas muestran los resultados o la salida generada por la ejecución de las celdas de código, como gráficos, tablas o texto.

¿Qué es un entorno de ejecución?
Un entorno de ejecución es el entorno computacional donde se ejecuta el código de un cuaderno Jupyter. Incluye el kernel que interpreta y ejecuta el código, así como los recursos de hardware (CPU, RAM, etc.) asignados para esa ejecución. El entorno de ejecución puede estar en tu máquina local, en un servidor remoto o en la nube.

¿Cuánto tiempo dura una sesión de un entorno?
La duración de una sesión de un entorno de ejecución depende de varios factores:

Configuración del servidor: Si estás usando Jupyter en un servidor remoto o en la nube, la duración de la sesión puede estar limitada por la configuración del servidor o los recursos disponibles.

Inactividad: Algunos entornos se configuran para cerrarse automáticamente después de un período de inactividad.

Uso de recursos: Si se consumen demasiados recursos, el entorno puede cerrarse para liberar memoria o CPU.

En general, una sesión puede durar desde unos minutos hasta horas, dependiendo de las políticas del entorno en el que estés trabajando.

"""

In [ ]:
"""Ejercicio 2

Las celdas de código de un cuaderno no solo permiten ejecutar instrucciones de Python. Utilizando el símbolo !
(signo de admiración) es posible ejecutar los comandos disponibles desde la línea de comandos de su sistema
operativo. De esta manera !ls o !dir (dependiendo el sistema operativo) listan los archivos de la carpeta actual y
!pip o !conda permiten administrar los paquetes python.
Experimente la ejecución de varios comandos del sistema operativo a través de celdas de código. Entre las
pruebas incluya la invocación de:
● python para determinar la versión instalada.
● pip show nombre (pandas, numpy, tensorflow, etc.) de paquete para saber la versión instalada.
● comandos que permitan crear y eliminar carpetas."""

In [ ]:
#Muestra directorio
!dir

#Muestra version
!python --version

#Muestra extensiones
!pip show pandas

!pip show numpy

!pip show tensorflow

!pip show matplotlib


#Crea y elimina carpetas
!mkdir nueva_carpeta



!rmdir  nueva_carpeta #/s /q


#!pip install matplotlib


sample_data
Python 3.10.12
Name: pandas
Version: 2.1.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License
        
        Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
        All rights reserved.
        
        Copyright (c) 2011-2023, Open source contributors.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
      

In [ ]:
"""Ejercicio 3
Dado que el entorno de ejecución de un cuaderno Colab tiene un límite de duración, es importante descargar o
salvar fuera del mismo los archivos que se generan.
Conecte su cuenta de Google Drive con Google Colab:

● Acceda a la url https://colab.research.google.com/ y autentíquese con su usuario Google. Cree un nuevo
cuaderno (notebook).

● Asocie Drive con Colab. Compruebe que Drive queda montado como una carpeta.

● Suba un pequeño archivo de texto a Drive (NO a Colab) y ábralo desde una celda de código Colab
utilizando el siguiente código:
ruta_arch = '....' # ruta y nombre a archivo a LEER desde su drive
f = open(ruta_arch, 'r') # abre archivo para leer
print(f.readlines()) # imprime contenido en pantalla
f.close() # cierra archivo


● Genere el siguiente archivo y guárdelo en su carpeta Drive, comprobando que efectivamente se ha creado
con el contenido esperado:
ruta_arch = '....' # ruta y nombre a archivo a ESCRIBIR en su drive
f = open(ruta_arch, 'w') # abre archivo para escribir
texto = 'Esta es una linea de texto\nEsta es otra línea de text'
f.writelines(texto) # escribe contenido en archivo
f.close() # cierra archivo

"""

In [ ]:
from google.colab import drive
drive.mount('/content/drive')




ruta_arch = '/content/drive/My Drive/Aprendizaje Automático Profundo (AAP)/Colab Notebooks/ElPepe.txt' # ruta y nombre a archivo a LEER desde su drive
f = open(ruta_arch, 'r') # abre archivo para leer
print(f.readlines()) # imprime contenido en pantalla
f.close() # cierra archivo

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['Puto el que lee']


In [ ]:
from google.colab import drive
drive.mount('/content/drive')



ruta_arch = '/content/drive/My Drive/Aprendizaje Automático Profundo (AAP)/Colab Notebooks/ElPepe2.txt' # ruta y nombre a archivo a ESCRIBIR en su drive
f = open(ruta_arch, 'w') # abre archivo para escribir
texto = 'Esta es una linea de texto\nEsta es otra línea de texto'
f.writelines(texto) # escribe contenido en archivo
f.close() # cierra archivo

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


--------------------------------------------------------------------------------------------------------------


In [ ]:
"""Repaso de Python
En esta sección tiene como objetivo hacer un pequeño repaso y proveer algunos recursos que faciliten el desarrollo
con Python. Para un tutorial desde cero puede consultarse el siguiente video
https://www.youtube.com/watch?v=zAIWnwqHGok. Para repasar estructuras de datos más utilizadas puede
consultarse https://www.youtube.com/watch?v=CCUNuqqn7PQ. Para una referencia rápida, el sitio
https://ipgp.github.io/scientific_python_cheat_sheet/ o https://www.pythoncheatsheet.org/ son buenas
alternativas. Aquí puede repasar temas como operadores, funciones, listas, tuplas, diccionarios, conjuntos, manejo
de strings y lectura/escritura de archivos, entre muchas otras."""


"""Ejercicio 1
Investigue/repase que son las listas, tuplas, conjuntos y diccionarios nativos de Python (puede consultar
https://www.youtube.com/watch?v=CCUNuqqn7PQ) . Utilizando los constructores para cada tipo de dato genere
códigos de ejemplo y recórralos imprimiendo sus valores."""

lista = [1,2,3,4,5]
touple = (1,2,3,4,5)
conjunto = {1,2,3,4,5}
diccionario = {"a" : "b", "b" : "c"}

for elemento in lista:
  print(elemento)
print()

for elemento in touple:
  print(elemento)
print()

for elemento in conjunto:
  print(elemento)
print()

for elemento in diccionario:
  print(diccionario["a"])
print()


"""Ejercicio 2
Genere el código necesario para recorrer simultáneamente 2 listas con la misma cantidad de elementos e imprima
los mismos utilizando un único for (tip: función zip).
"""



lista1 = [1, 2, 3]
lista2 = ['a', 'b', 'c']
lista3 = [True, False, True]

# Usar zip para combinar tres listas
combinado = zip(lista1, lista2, lista3)

# Convertir a una lista de tuplas
resultado = list(combinado)
print(resultado)

"""Opcion 2"""
lista1 = [1, 2, 3]
lista2 = ['a', 'b', 'c']

# Recorrer ambas listas simultáneamente
for num, letra in zip(lista1, lista2):
    print(f'Número: {num}, Letra: {letra}')




    """
Ejercicio 3
Implemente una función que a partir de la lista que recibe cómo parámetro, retorne una nueva lista sin elementos
repetidos. Compruebe su correcto funcionamiento.
"""

def purgatorio(lista):
  aux = set(lista)
  aux = list(aux)
  return aux



l = [1, 2, 2, 3, 4, 4, 5]

print("Lista original:", l)
print("Lista sin repetidos:", purgatorio(l))



"""
Ejercicio 4
Implemente una función que calcule la distancia entre 2 puntos (2D). Utilice la función sqrt del paquete math para
implementarla y compruebe el correcto funcionamiento de la misma.
"""
import math



def dist(ax,bx,ay,by):

  auxX= ax-bx
  auxY= ay-by

  return math.sqrt(auxX*auxX + auxY*auxY)


print("La distancia entre los puntos es:", dist(0,3,0,4))



"""
Version Chat

import math

def calcular_distancia(punto1, punto2):

    Calcula la distancia euclidiana entre dos puntos en 2D.

    :param punto1: Tupla con las coordenadas del primer punto (x1, y1).
    :param punto2: Tupla con las coordenadas del segundo punto (x2, y2).
    :return: La distancia entre los dos puntos.

    x1, y1 = punto1
    x2, y2 = punto2

    # Calcular la diferencia en las coordenadas
    delta_x = x2 - x1
    delta_y = y2 - y1

    # Calcular la distancia utilizando la fórmula
    distancia = math.sqrt(delta_x ** 2 + delta_y ** 2)

    return distancia

# Ejemplo de uso
punto_a = (1, 2)
punto_b = (4, 6)
print("La distancia entre los puntos es:", calcular_distancia(punto_a, punto_b))



Ejercicio 5
Investigue y escriba código que demuestre el funcionamiento de los “slices” en listas.
"""

lista=[1,2,3,4,5,6,7]
print("Primeros 2 " ,lista[0:2])
print("Primero, 3ro y 5to " ,lista[0:6:2])
print("Ultimos 4, + 7 ", lista[-5:-1] + [lista[len(lista)-1]])  #añadir corchetito

1
2
3
4
5

1
2
3
4
5

1
2
3
4
5

b
b

[(1, 'a', True), (2, 'b', False), (3, 'c', True)]
Número: 1, Letra: a
Número: 2, Letra: b
Número: 3, Letra: c
Lista original: [1, 2, 2, 3, 4, 4, 5]
Lista sin repetidos: [1, 2, 3, 4, 5]
La distancia entre los puntos es: 5.0
Primeros 2  [1, 2]
Primero, 3ro y 5to  [1, 3, 5]
Ultimos 4, + 7  [3, 4, 5, 6, 7]


In [ ]:
"""Biblioteca Numpy
Numpy es una biblioteca especializada para cálculo numérico y análisis de datos. Permite representar, a través del
tipo de datos array, colecciones de datos homogéneos (mismo tipo) en múltiples dimensiones y provee funciones
eficientes para su manipulación. Para una referencia rápida puede acceder al video:
https://www.youtube.com/watch?v=WxJr143Os-A
"""
"""
Ejercicio 1
Practique la creación de vectores, matrices y tensores y responda:
● ¿Qué diferencias hay entre los constructores, array, empty, full, zeros, ones, identity?
● ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por
defecto?¿Es siempre el mismo?
● ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?


Diferencias entre Constructores en NumPy:
  array: Convierte una secuencia en un array.
  empty: Crea un array sin inicializar los valores.
  full: Crea un array lleno con un valor específico.
  zeros: Crea un array lleno de ceros.
  ones: Crea un array lleno de unos.
  identity: Crea una matriz identidad.

"""
import numpy as np

# 1. np.array: Crea un array a partir de una lista o secuencia.
array = np.array([1, 2, 3])
print("np.array:", array)

# 2. np.empty: Crea un array sin inicializar valores.
empty_array = np.empty((2, 2))
print("\nnp.empty:\n", empty_array)

# 3. np.full: Crea un array y lo llena con un valor específico.
full_array = np.full((2, 2), 7)
print("\nnp.full:\n", full_array)

# 4. np.zeros: Crea un array lleno de ceros.
zeros_array = np.zeros((2, 3))
print("\nnp.zeros:\n", zeros_array)

# 5. np.ones: Crea un array lleno de unos.
ones_array = np.ones((2, 3))
print("\nnp.ones:\n", ones_array)

# 6. np.identity: Crea una matriz identidad (solo matrices cuadradas).
identity_matrix = np.identity(3)
print("\nnp.identity:\n", identity_matrix)
"""
Tipos de Datos en NumPy:
  Tipos soportados: int, float, complex, bool, str, object, y tipos específicos como int32, float64, etc.
  Tipo por defecto: float64.
Generación de Números Aleatorios:
  np.random.rand: Números aleatorios en [0, 1).
  np.random.randint: Enteros aleatorios en un rango.
  np.random.randn: Números aleatorios de distribución normal.
  np.random.choice: Elementos aleatorios de una lista/array.
"""


# 1. np.random.rand: Genera un array con números aleatorios en el rango [0, 1).
rand_array = np.random.rand(2, 3)
print("np.random.rand:\n", rand_array)

# 2. np.random.randint: Genera un array con enteros aleatorios en un rango especificado.
randint_array = np.random.randint(0, 10, size=(2, 3))
print("\nnp.random.randint:\n", randint_array)

# 3. np.random.randn: Genera un array con números aleatorios de distribución normal estándar.
randn_array = np.random.randn(2, 3)
print("\nnp.random.randn:\n", randn_array)

# 4. np.random.choice: Genera un array tomando elementos aleatorios de una lista o array dado.
choice_array = np.random.choice([10, 20, 30, 40], size=3)
print("\nnp.random.choice:\n", choice_array)

"""
3. Creación de un Tensor
Un tensor es un array de tres o más dimensiones.
"""

# Tensor de tres dimensiones (2x2x3)
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\nTensor:\n", tensor)



# Tensor de orden 4 con dimensiones 2x2x2x2
tensor_4 = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print("Tensor de orden 4:\n", tensor_4)





"""
Ejercicio 2
Investigue y ejemplifique las funciones relacionadas al tamaño de los arrays de Numpy:
● ¿Para qué sirven las funciones shape, len, ndim, size?
● ¿Qué tipos de datos pueden utilizarse? ¿En qué se diferencian? ¿Cuál es el tipo que se toma por
defecto?¿Es siempre el mismo?
● ¿Qué funciones se pueden utilizar para generar arreglos con números aleatorios?

"""


import numpy as np

# Creación de un array para demostrar las funciones relacionadas al tamaño
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Funciones relacionadas al tamaño
print("Shape:", arr.shape)  # Devuelve las dimensiones del array
print("Length:", len(arr))  # Devuelve el tamaño de la primera dimensión
print("Number of dimensions:", arr.ndim)  # Devuelve el número de dimensiones
print("Size:", arr.size)  # Devuelve el número total de elementos


"""
Tipos de Datos que Pueden Utilizarse
Tipos Comunes: int, float, complex, bool, str, y más específicos como int32, float64.
Diferencias: Los tipos específicos (int8, float32, etc.) tienen diferentes rangos y precisiones. Por ejemplo, int8 almacena enteros de -128 a 127, mientras que int32 tiene un rango mucho mayor.
Tipo por Defecto: Si no se especifica, el tipo por defecto es float64 para muchos constructores de arrays.
Variación: El tipo por defecto puede variar según la función utilizada y los datos proporcionados.
"""



# Generación de números aleatorios
rand_array = np.random.rand(2, 3)  # Array con valores aleatorios en [0, 1)
print("\nnp.random.rand:\n", rand_array)

randint_array = np.random.randint(0, 10, size=(2, 3))  # Array de enteros aleatorios
print("\nnp.random.randint:\n", randint_array)

randn_array = np.random.randn(2, 3)  # Array con distribución normal estándar
print("\nnp.random.randn:\n", randn_array)

choice_array = np.random.choice([10, 20, 30, 40], size=3)  # Selección aleatoria de una lista
print("\nnp.random.choice:\n", choice_array)




"""


Ejercicio 3
Practique funciones de agregación (sum, min, max, etc.) sobre vectores, matrices y tensores. Enumere y pruebe
todas las funciones que encuentre y responda:
● ¿Estas funciones se aplican a todos los datos del array o pueden realizarse sobre dimensiones
particulares? Ejemplifique.
"""

import numpy as np

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,5,4],[3,2,1]])
print("Suma",np.sum(a))
print("Suma",np.min(a))
print("Suma",np.max(b))



# Definición de arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[6, 5, 4], [3, 2, 1]])

# Funciones de agregación
print("Suma de a:", np.sum(a))     # Suma de todos los elementos de 'a'
print("Mínimo de a:", np.min(a))   # Valor mínimo en 'a'
print("Máximo de b:", np.max(b))   # Valor máximo en 'b'
print("Promedio de a:", np.mean(a)) # Promedio de todos los elementos de 'a'
print("Producto de a:", np.prod(a)) # Producto de todos los elementos de 'a'
print("Desviación estándar de a:", np.std(a)) # Desviación estándar de los elementos en 'a'

# Aplicación a dimensiones específicas
print("Suma de a a lo largo de las columnas (axis=0):", np.sum(a, axis=0))  # Suma por columnas
print("Suma de a a lo largo de las filas (axis=1):", np.sum(a, axis=1))    # Suma por filas


"""
Ejercicio 4
Investigue y realice ejemplos que utilicen funciones para manipular elementos de arreglos (append, insert, delete,
etc.) y arreglos entre sí (vstack, hstack, contacenate, etc.)

"""


# Manipulación de elementos
arr = np.array([1, 2, 3])

# Append
appended_arr = np.append(arr, [4, 5])
print("Array después de append:", appended_arr)

# Insert
inserted_arr = np.insert(arr, 1, [10, 20])
print("Array después de insert:", inserted_arr)

"""
# Delete
deleted_arr = np.delete(arr, [1, 3])
print("Array después de delete:", deleted_arr)
"""

# Combinación de arreglos
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

# vstack
vstack_arr = np.vstack((arr1, arr2))
print("Array después de vstack:\n", vstack_arr)

# hstack
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4], [5], [6]])
hstack_arr = np.hstack((arr1, arr2))
print("Array después de hstack:\n", hstack_arr)

# concatenate
concat_arr = np.concatenate((arr1, arr2), axis=1)
print("Array después de concatenate:\n", concat_arr)

"""
Explicación
Manipulación de Elementos:


np.append(): Agrega nuevos elementos al final del array.
np.insert(): Inserta elementos en la posición especificada.
np.delete(): Elimina elementos en las posiciones especificadas.
Combinación de Arreglos:

np.vstack(): Une arrays verticalmente, agregando filas.
np.hstack(): Une arrays horizontalmente, agregando columnas.
np.concatenate(): Une arrays a lo largo del eje especificado.



Ejercicio 5
Los arrays de numpy (así como las listas) proveen de un mecanismo versátil para hacer o referenciar una sección
de los mismos. Practique este mecanismo de acceso con vectores, matrices y tensores imprimiendo y
modificando distintas regiones de los mismos.
"""


# Crear un vector
vector = np.array([10, 20, 30, 40, 50])

# Acceso a elementos individuales
print("Elemento en la posición 2:", vector[2])  # 30

# Acceso a una sección (slicing)
print("Sección del vector desde el índice 1 hasta el 4:", vector[1:4])  # [20 30 40]

# Modificar una sección
vector[1:4] = [21, 31, 41]
print("Vector modificado:", vector)  # [10 21 31 41 50]



# Crear una matriz
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceso a un elemento
print("Elemento en la fila 1, columna 2:", matriz[1, 2])  # 6

# Acceso a una fila
print("Fila 1 de la matriz:", matriz[1])  # [4 5 6]

# Acceso a una columna
print("Columna 2 de la matriz:", matriz[:, 2])  # [3 6 9]

# Acceso a una sección (slicing)
print("Sección de la matriz (filas 0 a 1, columnas 1 a 2):\n", matriz[0:2, 1:3])
# [[2 3]
#  [5 6]]

# Modificar una sección
matriz[0:2, 1:3] = [[20, 30], [50, 60]]
print("Matriz modificada:\n", matriz)




np.array: [1 2 3]

np.empty:
 [[4.9e-323 9.9e-323]
 [1.5e-322 2.0e-322]]

np.full:
 [[7 7]
 [7 7]]

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

np.ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

np.identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.rand:
 [[0.32620807 0.71426154 0.49348777]
 [0.80673416 0.91429518 0.33340033]]

np.random.randint:
 [[6 4 7]
 [5 4 7]]

np.random.randn:
 [[-0.95733882  0.58172201  0.3581541 ]
 [ 0.67241413  1.26391062 -0.42980625]]

np.random.choice:
 [40 10 30]

Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Tensor de orden 4:
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Shape: (2, 3)
Length: 2
Number of dimensions: 2
Size: 6

np.random.rand:
 [[0.89011167 0.13720885 0.97785696]
 [0.74781917 0.47562449 0.46973714]]

np.random.randint:
 [[9 9 2]
 [1 0 2]]

np.random.randn:
 [[-0.60921798 -0.87736073 -1.02206885]
 [ 1.09747752  0.40009235 -1.17020019]]

np.random.choice:
 [30 10 40]
Suma 21
Suma 1
S

In [ ]:
"""

Biblioteca Pandas
Pandas es un paquete de Python que proporciona estructuras de datos rápidas, flexibles y expresivas, diseñadas
para trabajar con datos relacionales o etiquetados. Para comprender el objetivo de Pandas puede revisar el video
https://www.youtube.com/watch?v=gimfTyCNfGw a manera de introducción. Para realizar los ejercicios prácticos
puede consultar el video https://www.youtube.com/watch?v=5S01zSgE9GA.
Ejercicio 1
Investigue el funcionamiento del Dataframe de Pandas y cree uno con la información de la siguiente tabla:
Nombre Edad Pais
Juan 20 Argentina
María 26 Peru
Pedro 18 Brasil
José 22 Chile
Realice las siguientes operaciones:
● Imprimir los nombres de las columnas.
● Agregar a la tabla a Pablo que tiene 30 años y es originario de Colombia. Agregarlo de 2 formas diferentes.
● Eliminar de la tabla al Pedro repetido.
● Modificar los atributos de países que dicen “Peru” (sin acento) y reemplazarlos por “Perú” (con acento).



Ejercicio 2
Guarde en disco el dataframe del ejercicio anterior en los siguientes formatos:
● archivo con separación por delimitadores (tabulador como separador).
● archivo con separación por delimitadores (punto y coma como separador).
● archivo excel.
● archivo json.
"""







import pandas as pd

from google.colab import drive
drive.mount('/content/drive')



# Crear el DataFrame con los datos iniciales
data = {
    'Nombre': ['Juan', 'María', 'Pedro', 'José'],
    'Edad': [20, 26, 18, 22],
    'Pais': ['Argentina', 'Peru', 'Brasil', 'Chile']
}

df = pd.DataFrame(data)

# Imprimir los nombres de las columnas
print("Nombres de las columnas:", df.columns.tolist())

# Agregar a Pablo de dos formas
df.loc[len(df)] = ['Pablo', 30, 'Colombia']

# Crear el nuevo DataFrame con la fila que queremos agregar
new_row = pd.DataFrame({'Nombre': ['Pablo'], 'Edad': [30], 'Pais': ['Colombia']})

# Concatenar el DataFrame original con el nuevo
df = pd.concat([df, new_row], ignore_index=True)

# Eliminar a Pedro
df = df[df['Nombre'] != 'Pedro']

# Modificar países que dicen 'Peru' a 'Perú'
df['Pais'] = df['Pais'].replace('Peru', 'Perú')

print("\nDataFrame final:")
print(df)










# Asumiendo que df es el DataFrame del Ejercicio 1
# Guardar en diferentes formatos

# Archivo con separación por tabulador
df.to_csv('/content/drive/My Drive/Aprendizaje Automático Profundo (AAP)/Colab Notebooks/dataframe_tab.txt', sep='\t', index=False)

# Archivo con separación por punto y coma
df.to_csv('/content/drive/My Drive/Aprendizaje Automático Profundo (AAP)/Colab Notebooks/dataframe_semi.csv', sep=';', index=False)

# Archivo Excel
df.to_excel('/content/drive/My Drive/Aprendizaje Automático Profundo (AAP)/Colab Notebooks/dataframe.xlsx', index=False)

# Archivo JSON
df.to_json('/content/drive/My Drive/Aprendizaje Automático Profundo (AAP)/Colab Notebooks/dataframe.json', orient='records', lines=True)








Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Nombres de las columnas: ['Nombre', 'Edad', 'Pais']

DataFrame final:
  Nombre  Edad       Pais
0   Juan    20  Argentina
1  María    26       Perú
3   José    22      Chile
4  Pablo    30   Colombia
5  Pablo    30   Colombia
